# Generated by Django 3.2.9 on 2021-12-25 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 25, 19, 26, 8, 306468))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adduser')),
            ],
        ),
    ]
