# Generated by Django 4.2.2 on 2023-06-26 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211230_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 19, 58, 258287)),
        ),
    ]
