# Generated by Django 4.2.2 on 2023-06-27 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_addblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 18, 41, 36, 898238)),
        ),
    ]
